=== TanJinXian/FlowerFlower/public/dailySale.dtd
<!--/*
    Subject: BAIT3173 Integrative Programming
    Author: Tan Jin Xian RSD3 G7 17WMR09511
*/-->

<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT orderReport (order)*>
<!ELEMENT order (orderid , custName, orderDate, totalPayment)>
<!ELEMENT orderid (#PCDATA)>
<!ELEMENT custName (#PCDATA)>
<!ELEMENT orderDate (#PCDATA)>
<!ELEMENT totalPayment (#PCDATA)>

=== TanJinXian/FlowerFlower/public/dailySaleReport.xml
<?xml version="1.0"?>
<!DOCTYPE orderReport SYSTEM 'dailySale.dtd'>
<?xml-stylesheet type="text/xsl" href="dailySale.xsl"?>
<orderReport>
    <order>
        <orderid>1</orderid>
        <custName>John</custName>
        <orderDate>2018-08-10 13:17:17</orderDate>
        <totalPayment>40</totalPayment>
    </order>
    <order>
        <orderid>4</orderid>
        <custName>John</custName>
        <orderDate>2018-08-10 13:17:17</orderDate>
        <totalPayment>60</totalPayment>
    </order>
</orderReport>
